# Generated by Django 5.0.3 on 2024-07-15 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_constructionsite_store_constructionsiteimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionsite',
            name='responsible_person',
        ),
        migrations.AddField(
            model_name='responsibleperson',
            name='сonstruction_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.constructionsite'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='auto',
            field=models.CharField(default='-', max_length=255, verbose_name='Izoh'),
        ),
    ]
